requires:
- name: "base"
  category: "distro"
  version: ">=0"
- name: "luet"
  category: "system"
  version: ">=0"
steps:
- zypper in -y {{.Values.packages}}
# Removing packages that we don't need at the moment
#- zypper rm -y dracut ncurses-utils
- zypper rm -y ncurses-utils
# Cleans up cache
- zypper cc

- systemctl enable multi-user.target
- systemctl set-default multi-user.target
# XXX: To replace with dynamic mechanisms (cloud-init?)
# Setup a system default locale, for first boot
- echo "LANG=en_US.UTF-8" > /etc/locale.conf
- ln -s /usr/share/zoneinfo/UTC /etc/localtime
# Most of the size bloat come from kernel:

# cbd0cf3430f9:/luetbuild # rpm -qa --queryformat '%10{size} - %-25{name} \t %{version} \t %{os} \n' | sort -rh | head -25 | awk '{print $1/1024/1024, $2, $3, $4}' 
# 180.077 - kernel-default 5.10.5
# 12.4307 - glibc-locale-base 2.32
# 11.0003 - systemd 246.9
# 7.60744 - udev 246.9
# 7.49606 - file-magic 5.39
# 7.49081 - libzypp 17.25.5
# 7.10046 - zypper 1.14.41
# 5.95417 - glibc 2.32
# 5.9036 - coreutils 8.32
# 5.74755 - libsolv-tools 0.7.16
# 5.5852 - perl-base 5.32.0
# 5.58036 - gpg2 2.2.25
# 4.06195 - util-linux 2.35.1
# 4.05395 - kbd 2.3.0
# 3.5594 - libopenssl1_1 1.1.1h
# 3.39311 - gawk 5.1.0
# 3.01739 - shadow 4.8.1
# 2.68816 - rpm 4.15.1
# 2.6414 - elfutils 0.182
# 1.92351 - krb5 1.18.3
# 1.8625 - libstdc++6 10.2.1+git1030
# 1.71149 - libp11-kit0 0.23.20
# 1.69769 - libxml2-2 2.9.10
# 1.67791 - libglib-2_0-0 2.66.4
# 1.61761 - pam 1.5.1


unpack: true
excludes:
- ^/etc/shadow
- ^/etc/gshadow
- ^/etc/group
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/fstab
- ^/etc/passwd
- ^/etc/machineid
- ^/var/log
- ^/sys
- ^/proc
- ^/luetbuild
- ^/srv
- ^/root/.bash_history
- ^/run/reboot-needed

# Zypper
- ^/var/lib/zypp
- ^/var/cache/zypp
- ^/usr/share/zypper
- ^/usr/share/zypp
- ^/usr/share/zsh
- ^/usr/share/licenses/zypper
- ^/usr/bin/zypp-.*
- ^/usr/bin/zypper
- ^/usr/lib/zypp$
- ^/usr/lib/zypper
- ^/usr/lib/rpm
- ^/usr/bin/yzpper
- ^/usr/sbin/zypp-.*
- ^/usr/bin/zypp-.*
- ^/usr/bin/susetags2solv
- ^/run/zypp.*
- ^/etc/zypp
- ^/usr/bin/rpm.*
- ^/var/lib/rpm

# Build deps that got thrown-in by zypper
# XXX: To keep until https://github.com/mudler/luet/issues/173 is delivered,
# or we either create another luet repository for runtime deps
- ^/usr/share/bison
- ^/usr/share/automake
- ^/usr/share/autoconf
- ^/usr/share/aclocal
- ^/usr/share/texinfo
- ^/usr/share/libtool

- texinfo.mo
- git.mo
- flex.mo
- ^/usr/libexec/git
- ^/usr/lib64/pkgconfig
- ^/usr/lib64/ldscripts
- ^/usr/lib64/gcc
- ^/usr/bin/git.*
- ^/usr/bin/gcc.*
- ^/usr/bin/flex.*
- ^/usr/bin/autom.*
- ^/usr/bin/autoconf.*
- ^/usr/bin/bison.*
- ^/usr/bin/libtool.*
- ^/usr/x86_64-suse-linux
- ^/usr/lib64/rpm-plugins
# Yast
- ^/var/lib/YaST2

# Perl
- ^/usr/bin/perl.*
- ^/usr/lib/perl.*

# General
- ^/usr/include
- ^/usr/local
- ^/root