#!/bin/bash


event="$1"
payload="$2"

if [ "$event" == "image.post.build" ]; then
  image=$(echo "$payload" | jq -r .data | jq -r .ImageName )
  jq --arg key0 "state" --arg value0 "$image signed" \
   --arg key1   "data"  --arg value1 "" \
   '. | .[$key0]=$value0 | .[$key1]=$value1 ' \
  <<<'{}'
fi
