name: "Default deployment"
stages:
  rootfs.after:
    - if: '[ -f "/run/cos/recovery_mode" ]'
      name: "Repart image"
      layout:
        device:
          label: COS_RECOVERY
        add_partitions:
          - fsLabel: COS_STATE
            size: 9192
            pLabel: state
            filesystem: ext4
          - fsLabel: COS_PERSISTENT
            pLabel: persistent
            filesystem: ext4
  # Azure does not allow to ssh with root user so we need to create an user to provision the image correctly
  network:
    - if: '[ -f "/run/cos/recovery_mode" ]'
      commands:
        - useradd "packer" -m -u 1500 # Add packer user
        - echo "packer:cos" | chpasswd # change packer pass
        - usermod -a -G root packer # add packer to root group
    - if: '[ -f "/run/cos/recovery_mode" ]'
      files:
        - path: /etc/sudoers.d/wheel # set passwordless sudo
          content: "packer ALL = (ALL) NOPASSWD: ALL"