requires:
- name: "base"
  category: "distro"
  version: ">=0"

steps:
- zypper in -y -f kernel-vanilla-{{.Values.version}}

includes:
# Kernel
- /boot$
- /boot/vmlinux-.*
- /boot/vmlinuz-.*
- /boot/System.map-.*
- /lib$
- /lib/modules$
- /lib/modules/{{ .Values.kernel_id }}$
- /lib/modules/{{ .Values.kernel_id }}/.*