# Rootfs cOS OEM configuration file
#
# This file is part of cOS and will get reset during upgrades.
#
# Before you change this file manually,
# consider copying this file to /usr/local/cloud-config or
# copy the file with a prefix starting by 90, e.g. /oem/91_custom.yaml
name: "Rootfs Layout Settings"
stages:
  rootfs:
    - environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: "LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local"
        OVERLAY: "tmpfs:25%"
#       DEBUG_RW: "true"
  initramfs:
    - if: '[ -z "$(blkid -L COS_SYSTEM || true)" ]'
      name: "Persist /etc/machine-id"
      commands:
      - |
        # persist machine-id
        if [ -s /usr/local/etc/machine-id ]; then
          cat /usr/local/etc/machine-id > /etc/machine-id
        else
          mkdir -p /usr/local/etc
          cp /etc/machine-id /usr/local/etc
        fi
    - if: '[ -z "$(blkid -L COS_SYSTEM || true)" ]'
      name: "Persist ssh fingerprint"
      commands:
      - |
        # persist ssh fingerprint
        if [ -d /usr/local/etc/ssh ]; then
          mkdir /etc/ssh || true
          for i in /usr/local/etc/ssh/*.pub; do cp -rf $i /etc/ssh; done
        fi
  network:
    - if: '[ -z "$(blkid -L COS_SYSTEM || true)" ]'
      name: "Load persisted ssh fingerprint"
      commands:
      - |
        # load ssh fingerprint
        if [ ! -d /usr/local/etc/ssh ]; then
          systemctl start sshd
          mkdir /usr/local/etc/ssh || true
          for i in /etc/ssh/*.pub; do cp -rf $i /usr/local/etc/ssh; done
        fi