requires:
  - name: "cos"
    category: "system"
    version: ">=0"

steps:
  - mkdir /grub-artifacts
{{ if .Values.distribution }}
  {{if eq .Values.distribution "opensuse" }}
  - cp -rf /usr/share/grub2/* /grub-artifacts
  {{else}}
  - cp -rf /usr/share/grub/* /grub-artifacts
  {{end}}
{{end}}

package_dir: /grub-artifacts