requires:
- name: "tumbleweed"
  category: "distro"
  version: ">=0"

steps:
- zypper in -y kernel-default

includes:
# Kernel
- /boot$
- /boot/vmlinux-.*
- /boot/vmlinuz-.*
- /boot/System.map-.*

- /lib$
- /lib/modules$
- /lib/modules/{{ .Values.kernel_id }}$
- /lib/modules/{{ .Values.kernel_id }}/modules.*
- /lib/modules/{{ .Values.kernel_id }}/source
- /lib/modules/{{ .Values.kernel_id }}/build

# OverlayFS
- /lib/modules/{{ .Values.kernel_id }}/kernel$
- /lib/modules/{{ .Values.kernel_id }}/kernel/fs$
- /lib/modules/{{ .Values.kernel_id }}/kernel/fs/mbcache.ko
- /lib/modules/{{ .Values.kernel_id }}/kernel/fs/overlayfs$
- /lib/modules/.*/kernel/fs/overlayfs/.*
- /lib/modules/.*/kernel/lib$
- /lib/modules/.*/kernel/lib/.*

# Crypto
- /lib/modules/.*/kernel/crypto$
- /lib/modules/.*/kernel/crypto/.*

# EXT
- /lib/modules/.*/kernel/fs/ext2$
- /lib/modules/.*/kernel/fs/ext4$
- /lib/modules/.*/kernel/fs/jbd2$
- /lib/modules/.*/kernel/fs/ext2/.*
- /lib/modules/.*/kernel/fs/ext4/.*
- /lib/modules/.*/kernel/fs/jbd2/.*

# USB
- /lib/modules/.*/kernel$
- /lib/modules/.*/kernel/drivers$
- /lib/modules/.*/kernel/drivers/usb$
- /lib/modules/.*/kernel/drivers/usb/.*
- /lib/modules/.*/kernel/drivers/usb/storage$
- /lib/modules/.*/kernel/drivers/usb/storage/.*
- /lib/modules/.*/kernel/drivers/usb/host$
- /lib/modules/.*/kernel/drivers/usb/host/.*
- /lib/modules/.*/kernel/drivers/usb/common$
- /lib/modules/.*/kernel/drivers/usb/common/.*

- /lib/modules/.*/kernel/drivers/hid$
- /lib/modules/.*/kernel/drivers/hid/.*
- /lib/modules/.*/kernel/drivers/hid/usbhid$
- /lib/modules/.*/kernel/drivers/hid/usbhid/.*
- /lib/modules/.*/kernel/drivers/hid/i2c-hid$
- /lib/modules/.*/kernel/drivers/hid/i2c-hid/.*


# Input
- /lib/modules/.*/kernel/drivers/input$
- /lib/modules/.*/kernel/drivers/input/.*
- /lib/modules/.*/kernel/drivers/input/keyboard$
- /lib/modules/.*/kernel/drivers/input/keyboard/.*
- /lib/modules/.*/kernel/drivers/input/misc$
- /lib/modules/.*/kernel/drivers/input/misc/.*
- /lib/modules/.*/kernel/drivers/input/mouse$
- /lib/modules/.*/kernel/drivers/input/mouse/.*

# block
- /lib/modules/.*/kernel/drivers/block$
- /lib/modules/.*/kernel/drivers/block/.*

# ATA
- /lib/modules/.*/kernel/drivers/ata$
- /lib/modules/.*/kernel/drivers/ata/.*

# md
- /lib/modules/.*/kernel/drivers/md$
- /lib/modules/.*/kernel/drivers/md/.*

# firewire
- /lib/modules/.*/kernel/drivers/firewire$
- /lib/modules/.*/kernel/drivers/firewire/.*

# virtio
- /lib/modules/.*/kernel/drivers/virtio$
- /lib/modules/.*/kernel/drivers/virtio/.*