image: "{{.Values.image}}"

steps:
{{if .Values.is_opensuse}}
- zypper in -y --no-recommends {{.Values.leap_packages}} {{.Values.common_packages}} {{.Values.kernel_package}}
- zypper cc
{{else if .Values.is_fedora}}
- echo "install_weak_deps=False" >> /etc/dnf/dnf.conf
- dnf install -y {{.Values.fedora_packages}} {{.Values.common_packages}} {{.Values.kernel_package}}
- dnf clean all
- |
    kernel=$(ls /boot/vmlinuz-* | head -n1) && \
    ln -sf "${kernel#/boot/}" /boot/vmlinuz
{{end}}
- kernel=$(ls /lib/modules | head -n1) && depmod -a "${kernel}"
