requires:
- name: "golang"
  category: "build"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
prelude:
- |
   git clone https://github.com/k3s-io/k3s.git && cd k3s && \
{{- if .Values.branch }}
   git checkout {{.Values.branch}} -b build
{{- else }}
   git checkout v{{.Values.version}} -b build
{{- end }}
- |
   zypper in -y libseccomp-devel
# && \
# cd k3s && go mod vendor
-  cd k3s && ./scripts/build
steps:
- cd k3s && cp -rfv bin/* /usr/bin/