requires:
- name: "golang"
  category: "build"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
- GOPATH=/go
- GO111MODULE=off
prelude:
- |
   mkdir -p /go/src/github.com/rancher && \
   git clone https://github.com/k3s-io/k3s.git /go/src/github.com/rancher/k3s && cd /go/src/github.com/rancher/k3s && \
{{- if .Values.branch }}
   git checkout {{.Values.branch}} -b build
{{- else }}
   git checkout v{{.Values.version}} -b build
{{- end }}
# Build deps required only for k3s
- |
   zypper in -y libseccomp-devel
- cd /go/src/github.com/rancher/k3s && ./scripts/build
steps:
- cd /go/src/github.com/rancher/k3s && cp -rfv bin/* /usr/bin/