requires:
- name: "base"
  category: "distro"
  version: ">=0"
- name: "default"
  category: "kernel"
  version: "5.3.18"

steps:
- |
    dracut --verbose --no-hostonly --no-hostonly-cmdline --xz \
        -f /boot/initrd-{{.Values.kernel_id}} --add " dmsquash-live " \
        --include "/luetbuild/cos-config-launcher.sh" \
        "/lib/dracut/hooks/pre-pivot/30cos-config.sh" {{.Values.kernel_id}} && \
    ln -sf initrd-{{.Values.kernel_id}} /boot/initrd
