requires:
- name: "base"
  category: "distro"
  version: ">=0"
- name: "default"
  category: "kernel"
  version: ">=0"

steps:
- |
    kerver=$(ls /lib/modules/ sort -Vr | head -n1) && \
    dracut --verbose --no-hostonly --no-hostonly-cmdline --xz \
        -f /boot/initrd-$kerver --add " dmsquash-live " \
        --include "/luetbuild/cos-config-launcher.sh" "/lib/dracut/hooks/pre-pivot/30cos-config.sh" $kerver && \
    ln -sf initrd-$kerver /boot/initrd
