# Default cOS OEM configuration file
stages:
    fs.after:
     - name: "Setup distro"
       commands:
       - /usr/bin/systemd-firstboot --keymap=us
       - /usr/bin/systemd-firstboot --locale=en_US.UTF-8
       - /usr/bin/systemd-firstboot --timezone=UTC
