# Default cOS OEM configuration file
stages:
   initramfs.after:
     - name: "Setup network"
       dns:
         path: /etc/resolv.conf
         nameservers:
         - 8.8.8.8
         - 1.1.1.1
       commands:
       - mkdir /etc/ssl
       - ln -s /var/lib/ca-certificates/pem /etc/ssl/certs
       - ln -s /var/lib/ca-certificates/ca-bundle.pem /etc/ssl/ca-bundle.pem
       files:
        - path: /etc/hostname
          content: "cos"
          permissions: 0644
          owner: 0
          group: 0
        - path: /etc/hosts
          content: |
                     #
                     # hosts         This file describes a number of hostname-to-address
                     #               mappings for the TCP/IP subsystem.  It is mostly
                     #               used at boot time, when no name servers are running.
                     #               On small systems, this file can be used instead of a
                     #               "named" name server.
                     # Syntax:
                     #    
                     # IP-Address  Full-Qualified-Hostname  Short-Hostname
                     #

                     127.0.0.1       localhost

                     # special IPv6 addresses
                     ::1             localhost ipv6-localhost ipv6-loopback

                     fe00::0         ipv6-localnet

                     ff00::0         ipv6-mcastprefix
                     ff02::1         ipv6-allnodes
                     ff02::2         ipv6-allrouters
                     ff02::3         ipv6-allhosts
          permissions: 0644
          owner: 0
          group: 0
