requires:
- name: "base"
  category: "distro"
  version: ">=0"

package_dir: /{{.Values.name}}

prelude:
  {{ if .Values.distribution }}
  {{if eq .Values.distribution "opensuse" }}
- zypper install -y autoconf libtool git gcc make
  {{else if eq .Values.distribution "fedora" }}
- dnf install -y autoconf libtool git gcc make
  {{else if eq .Values.distribution "ubuntu" }}
- apt-get update
- apt-get install -y autoconf libtool git gcc make
  {{end}}
  {{end}}

steps:
{{ if .Values.arch }}
  {{ if eq .Values.arch "aarch64" }}
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  mkdir -p /luetbuild/{{ ( index .Values.labels "github.repo" ) }} && \
  cd /luetbuild/{{ ( index .Values.labels "github.repo" ) }} && \
  git clone https://github.com/{{ ( index .Values.labels "github.owner" ) }}/{{ ( index .Values.labels "github.repo" ) }} && \
  cd {{ ( index .Values.labels "github.repo" ) }} && git checkout jq-"$PACKAGE_VERSION" -b build && \
  git submodule update --init && autoreconf -fi && ./configure --with-oniguruma=builtin --disable-maintainer-mode && \
  make LDFLAGS=-all-static && \
  mkdir -p /${PACKAGE_NAME}/usr/bin && \
  cp ./${PACKAGE_NAME} /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
  chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
  {{else}}
- | 
   PACKAGE_VERSION=${PACKAGE_VERSION%\-*} && \
   mkdir -p /${PACKAGE_NAME}/usr/bin && \
   curl -L https://github.com/{{ ( index .Values.labels "github.owner" ) }}/{{ ( index .Values.labels "github.repo" ) }}/releases/download/${PACKAGE_NAME}-${PACKAGE_VERSION}/jq-linux64 -o /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME} && \
   chmod +x /${PACKAGE_NAME}/usr/bin/${PACKAGE_NAME}
  {{ end }}
{{ end }}