requires:
- name: "uroot"
  category: "system"
  version: ">=0"
- category: "kernel"
  name: "vanilla"
  version: ">=0"
env:
- PATH=$PATH:/usr/local/go/bin
- GOPATH=/luetbuild/go
- GO111MODULE=off
- CGO_ENABLED=0

prelude:
- mkdir /boot || true
- cp -rf uinit $GOPATH/src/uinit
steps:

- mkdir modules
- find /lib/modules/**/kernel/fs -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/lib -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/crypto -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/crypto -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/drivers/usb -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/drivers/hid -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/drivers/input -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/drivers/block -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/drivers/ata -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/drivers/md -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/drivers/virtio -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/drivers/cdrom -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/drivers/scsi -type f -name '*.ko.xz' -exec cp {} ./modules \;

# Ethernet + address family
- find /lib/modules/**/kernel/drivers/net/ethernet -type f -name '*.ko.xz' -exec cp {} ./modules \;
- find /lib/modules/**/kernel/net/packet -type f -name '*.ko.xz' -exec cp {} ./modules \;

# Unxz it until we replace default u-root init with ours (at the moment we provide just uinit)
- find ./modules -type f -name '*.ko.xz' -exec unxz {} \;
- |
   u-root \
   -files "/luetbuild/loader.sh:/loader" \
   -files "/luetbuild/modules:/lib/modules" \
   -format=cpio -build=bb -o initramfs.cpio core uinit/
# This embeds alla available modules, plus native stuff
# - |
#    u-root -files "/lib/modules/" \
#           -files "/sbin/modprobe" \
#           -files "/sbin/depmod" \
#           -format=cpio -build=bb -o initramfs.cpio core uinit/
- |
   xz --check=crc32 -9 --lzma2=dict=1MiB \
      --stdout initramfs.cpio \
      | dd conv=sync bs=512 \
      of=/boot/initramfs

excludes:
- ^/luetbuild
- ^/root