requires:
- name: "tumbleweed"
  category: "distro"
  version: ">=0"

prelude:
- zypper rm -y coreutils findutils

steps:
- zypper in -y --replacefiles {{.Values.zypper_packages}}
- mv -fv /usr/bin/busybox-static /usr/bin/busybox
# sh by default symlinks to /etc/alternatives/ssh, and in this busybox which is used during initramfs,
# we don't really need that
- rm -rfv /usr/bin/sh && ln -s /usr/bin/busybox /usr/bin/sh

excludes:
- ^/etc
- ^/var/cache
- ^/var/lib

# Busybox is a bit special:
# zypper doesn't allow us to remove moar from the base image, as zypper depends on some packages from it.
# in this case, we extract the required busybox pieces only
# TODO: Have a look at compiling it from source. It's much more easier than consuming the one from openSUSE
#       repositories
unpack: true
includes:
- /bin$|/sbin$|/usr$|/usr/sbin$|/usr/bin$
- /bin/arch
- /bin/arping
- /bin/basename
- /bin/cat
- /bin/chattr
- /bin/chgrp
- /bin/chmod
- /bin/chown
- /bin/chvt
- /bin/cp
- /bin/cpio
- /bin/date
- /bin/dd
- /bin/deallocvt
- /bin/df
- /bin/dmesg
- /bin/dnsdomainname
- /bin/echo
- /bin/ed
- /bin/false
- /bin/fatattr
- /bin/find
- /bin/fsync
- /bin/gunzip
- /bin/gzip
- /bin/hostname
- /bin/ifconfig
- /bin/iostat
- /bin/ip
- /bin/kill
- /bin/ln
- /bin/logger
- /bin/login
- /bin/ls
- /bin/lsattr
- /bin/lsmod
- /bin/lzop
- /bin/md5sum
- /bin/mkdir
- /bin/mknod
- /bin/mktemp
- /bin/more
- /bin/mount
- /bin/mpstat
- /bin/mv
- /bin/netstat
- /bin/openvt
- /bin/ping
- /bin/ping6
- /bin/pwd
- /bin/readlink
- /bin/rm
- /bin/rmdir
- /bin/route
- /bin/setfont
- /bin/setkeycodes
- /bin/setlogcons
- /bin/showkey
- /bin/sleep
- /bin/sort
- /bin/stat
- /bin/stty
- /bin/sh
- /bin/su
- /bin/sync
- /bin/tar
- /bin/touch
- /bin/true
- /bin/umount
- /bin/uname
- /bin/usleep
- /bin/vi
- /bin/zcat
- /sbin/arp
- /sbin/blkid
- /sbin/depmod
- /sbin/ether-wake
- /sbin/findfs
- /sbin/fsck
- /sbin/insmod
- /sbin/ip
- /sbin/iptunnel
- /sbin/killall5
- /sbin/loadkmap
- /sbin/losetup
- /sbin/lsmod
- /sbin/mdev
- /sbin/mkdosfs
- /sbin/mke2fs
- /sbin/mkfs.ext2
- /sbin/mkfs.vfat
- /sbin/mkswap
- /sbin/modinfo
- /sbin/modprobe
- /sbin/nameif
- /sbin/nologin
- /sbin/rmmod
- /sbin/setconsole
- /sbin/slattach
- /sbin/tunctl
- /sbin/uevent
- /sbin/vconfig
- /sbin/zcip
- /usr/bin/\[
- /usr/bin/ar
- /usr/bin/arch
- /usr/bin/arping
- /usr/bin/ash
- /usr/bin/base64
- /usr/bin/basename
- /usr/bin/bc
- /usr/bin/beep
- /usr/bin/bunzip2
- /usr/bin/busybox
- /usr/bin/busybox-static
- /usr/bin/busybox.install
- /usr/bin/bzcat
- /usr/bin/bzip2
- /usr/bin/cal
- /usr/bin/cat
- /usr/bin/chcon
- /usr/bin/chgrp
- /usr/bin/chmod
- /usr/bin/chown
- /usr/bin/chroot
- /usr/bin/chvt
- /usr/bin/cksum
- /usr/bin/cmp
- /usr/bin/comm
- /usr/bin/cp
- /usr/bin/cpio
- /usr/bin/cryptpw
- /usr/bin/cut
- /usr/bin/date
- /usr/bin/dd
- /usr/bin/deallocvt
- /usr/bin/df
- /usr/bin/diff
- /usr/bin/dirname
- /usr/bin/dmesg
- /usr/bin/dnsdomainname
- /usr/bin/dos2unix
- /usr/bin/du
- /usr/bin/echo
- /usr/bin/ed
- /usr/bin/env
- /usr/bin/envdir
- /usr/bin/expand
- /usr/bin/expr
- /usr/bin/factor
- /usr/bin/fallocate
- /usr/bin/false
- /usr/bin/find
- /usr/bin/flock
- /usr/bin/fold
- /usr/bin/getopt
- /usr/bin/groups
- /usr/bin/gunzip
- /usr/bin/gzip
- /usr/bin/head
- /usr/bin/hexdump
- /usr/bin/hexedit
- /usr/bin/hostid
- /usr/bin/hostname
- /usr/bin/hush
- /usr/bin/id
- /usr/bin/ifconfig
- /usr/bin/install
- /usr/bin/ipcrm
- /usr/bin/ipcs
- /usr/bin/kill
- /usr/bin/last
- /usr/bin/less
- /usr/bin/link
- /usr/bin/linux32
- /usr/bin/linux64
- /usr/bin/ln
- /usr/bin/logger
- /usr/bin/logname
- /usr/bin/ls
- /usr/bin/lsmod
- /usr/bin/lsof
- /usr/bin/lspci
- /usr/bin/lsscsi
- /usr/bin/lsusb
- /usr/bin/man
- /usr/bin/md5sum
- /usr/bin/mesg
- /usr/bin/mkdir
- /usr/bin/mkfifo
- /usr/bin/mknod
- /usr/bin/mkpasswd
- /usr/bin/mktemp
- /usr/bin/more
- /usr/bin/mount
- /usr/bin/mountpoint
- /usr/bin/mv
- /usr/bin/nc
- /usr/bin/netstat
- /usr/bin/nice
- /usr/bin/nl
- /usr/bin/nmeter
- /usr/bin/nohup
- /usr/bin/nproc
- /usr/bin/nsenter
- /usr/bin/nslookup
- /usr/bin/od
- /usr/bin/openvt
- /usr/bin/passwd
- /usr/bin/paste
- /usr/bin/patch
- /usr/bin/ping
- /usr/bin/ping6
- /usr/bin/printenv
- /usr/bin/printf
- /usr/bin/pscan
- /usr/bin/pwd
- /usr/bin/readlink
- /usr/bin/realpath
- /usr/bin/renice
- /usr/bin/resize
- /usr/bin/rev
- /usr/bin/rm
- /usr/bin/rmdir
- /usr/bin/route
- /usr/bin/runcon
- /usr/bin/script
- /usr/bin/scriptreplay
- /usr/bin/seq
- /usr/bin/setarch
- /usr/bin/setfattr
- /usr/bin/setfont
- /usr/bin/setkeycodes
- /usr/bin/setlogcons
- /usr/bin/setpriv
- /usr/bin/setsid
- /usr/bin/sha1sum
- /usr/bin/sha256sum
- /usr/bin/sha3sum
- /usr/bin/sha512sum
- /usr/bin/showkey
- /usr/bin/shred
- /usr/bin/shuf
- /usr/bin/sleep
- /usr/bin/smemcap
- /usr/bin/sort
- /usr/bin/split
- /usr/bin/ssl_client
- /usr/bin/stat
- /usr/bin/strings
- /usr/bin/stty
- /usr/bin/sh
- /usr/bin/su
- /usr/bin/sum
- /usr/bin/sync
- /usr/bin/tac
- /usr/bin/tail
- /usr/bin/tar
- /usr/bin/tee
- /usr/bin/telnet
- /usr/bin/test
- /usr/bin/tftp
- /usr/bin/time
- /usr/bin/timeout
- /usr/bin/touch
- /usr/bin/tr
- /usr/bin/true
- /usr/bin/truncate
- /usr/bin/tty
- /usr/bin/ttysize
- /usr/bin/umount
- /usr/bin/uname
- /usr/bin/uncompress
- /usr/bin/unexpand
- /usr/bin/uniq
- /usr/bin/unix2dos
- /usr/bin/unlink
- /usr/bin/unshare
- /usr/bin/unzip
- /usr/bin/uptime
- /usr/bin/users
- /usr/bin/uudecode
- /usr/bin/uuencode
- /usr/bin/vi
- /usr/bin/vlock
- /usr/bin/wall
- /usr/bin/wc
- /usr/bin/which
- /usr/bin/who
- /usr/bin/whoami
- /usr/bin/whois
- /usr/bin/xargs
- /usr/bin/xxd
- /usr/bin/yes
- /usr/bin/zcat
- /usr/bin/zgrep
- /usr/bin/zip
- /usr/bin/zipcloak
- /usr/bin/zipnote
- /usr/bin/zipsplit
# - usr/lib/sysusers.d/system-user-nobody.conf
# - usr/lib64/libcrypt.so.1
# - usr/lib64/libcrypt.so.1.1.0
# - usr/lib64/libowcrypt.so.1
# - usr/lib64/libsepol.so.1
- /usr/sbin/addgroup
- /usr/sbin/adduser
- /usr/sbin/arp
- /usr/sbin/blkid
- /usr/sbin/brctl
- /usr/sbin/chpasswd
- /usr/sbin/delgroup
- /usr/sbin/deluser
- /usr/sbin/depmod
- /usr/sbin/ether-wake
- /usr/sbin/findfs
- /usr/sbin/fsck
- /usr/sbin/ifdown
- /usr/sbin/ifenslave
- /usr/sbin/ifup
- /usr/sbin/insmod
- /usr/sbin/ip
- /usr/sbin/ipaddr
- /usr/sbin/iplink
- /usr/sbin/ipneigh
- /usr/sbin/iproute
- /usr/sbin/iprule
- /usr/sbin/iptunnel
- /usr/sbin/loadfont
- /usr/sbin/losetup
- /usr/sbin/lsmod
- /usr/sbin/mkswap
- /usr/sbin/modinfo
- /usr/sbin/modprobe
- /usr/sbin/nameif
- /usr/sbin/nbd-client
- /usr/sbin/nologin
- /usr/sbin/rmmod
- /usr/sbin/slattach
- /usr/sbin/sulogin
- /usr/sbin/syslogd
- /usr/sbin/sysusers2shadow
- /usr/sbin/tc
- /usr/sbin/traceroute
- /usr/sbin/traceroute6
- /usr/sbin/vconfig
# - usr/share/licenses/busybox/
# - usr/share/licenses/busybox/LICENSE
# - usr/share/licenses/busybox-static/LICENSE