stages:
   network:
     - name: "Setup k3s"
       directories:
       - path: "/usr/local/bin"
         permissions: 0755
         owner: 0
         group: 0
       commands:
       - |
            curl -sfL https://get.k3s.io | \
            INSTALL_K3S_VERSION="v1.20.4+k3s1" \
            INSTALL_K3S_EXEC="--data-dir /usr/local/rancher/k3s" \
            sh -
       systemctl:
        start:
        - iscsid
     - name: "Setup Longhorn"
       commands:
       - |
          curl https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/deploy/longhorn.yaml | \
          sed -e 's/#- name: KUBELET_ROOT_DIR/- name: KUBELET_ROOT_DIR/g' -e 's$#  value: /var/lib/rancher/k3s/agent/kubelet$  value: /var/lib/kubelet$g'  | \
          sed -e 's|default-data-path:|default-data-path: /usr/local/rancher/longhorn|g' | \
          k3s --data-dir /usr/local/rancher/k3s kubectl apply -f -
       commands:
       - |
          if [ ! -e "/usr/local/bin/helm" ]; then
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          fi
     - name: "Harvester"
       directories:
       - path: "/run/harvester"
         permissions: 0755
         owner: 0
         group: 0
       commands:
       - |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            curl -L https://github.com/rancher/harvester/archive/refs/heads/master.tar.gz | tar -xz -C /run/harvester && \
            cd /run/harvester/**/deploy/charts && \
            k3s --data-dir /usr/local/rancher-k3s kubectl create ns harvester-system && \
            helm install harvester harvester --namespace harvester-system --set minio.persistence.storageClass=longhorn

name: "Rancher Harvester is an open source hyper-converged infrastructure (HCI) software built on Kubernetes. It is an open source alternative to vSphere and Nutanix."
