requires:
- name: "base"
  category: "distro"
  version: ">=0"

prelude:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
- zypper in -y wget
{{else if eq .Values.distribution "fedora" }}
- dnf install -y wget
{{else if eq .Values.distribution "ubuntu" }}
- apt-get install -y wget || true
{{end}}
{{end}}
- wget http://kernel.org/pub/linux/utils/boot/syslinux/syslinux-{{.Values.version}}.tar.xz
- mkdir -p /syslinux
- tar -xvf syslinux-{{.Values.version}}.tar.xz -C /syslinux
steps:
- mkdir -p /output/boot/syslinux
- mv /syslinux/syslinux-{{.Values.version}}/bios/core/isolinux.bin /output/boot/syslinux
- mv /syslinux/syslinux-{{.Values.version}}/bios/com32/elflink/ldlinux/ldlinux.c32 /output/boot/syslinux
- mv /syslinux/syslinux-{{.Values.version}}/bios/mbr/isohdpfx.bin /output/boot/syslinux
package_dir: /output

requires:
- name: "base"
  category: "distro"
  version: ">=0"
