requires:
- name: "base"
  category: "distro"
  version: ">=0"

package_dir: /{{.Values.name}}
prelude:
- |
   mkdir -p /${PACKAGE_NAME}/usr/sbin
steps:
- cp -rfv init-skel.sh /${PACKAGE_NAME}/usr/sbin/init-skel
- chmod +x /${PACKAGE_NAME}/usr/sbin/init-skel
- mkdir -p /${PACKAGE_NAME}/etc/skel.defaults/
- cp -rfv rootfs/* /${PACKAGE_NAME}/etc/skel.defaults/
- cp -rfv skel /${PACKAGE_NAME}/etc/
- mkdir /${PACKAGE_NAME}/mnt && touch /${PACKAGE_NAME}/mnt/.keep
