name: Build cOS
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - flavor: "opensuse"
    env:
      FLAVOR: ${{ matrix.flavor }}
    steps:
      - uses: actions/checkout@v2

      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: build-${{ matrix.flavor }}-${{ github.run_id }}
          path: build
      - name: setup-docker
        if: always()
        uses: docker-practice/actions-setup-docker@master
      - name: Install deps
        if: always()
        run: |
          sudo -E make deps
      - name: Build packages 🔧
        if: always()
        run: |
          sudo -E make build
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.flavor }}-${{ github.run_id }}
          path: build
          if-no-files-found: error