name: Build cOS
on:
  schedule:
    - cron:  '0 20 * * *'
  push:
    paths:
    - 'conf/**'
    - 'packages/**'
    - '.github/workflows/**'
    - 'tests/'
    - 'Makefile'
  pull_request:
    paths:
    - 'conf/**'
    - 'packages/**'
    - '.github/workflows/**'
    - 'Makefile'
    - 'tests/'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - flavor: "opensuse"
         - flavor: "fedora"
    env:
      FLAVOR: ${{ matrix.flavor }}
    steps:
    - uses: actions/checkout@v2

    - run: |
        git fetch --prune --unshallow

    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1

    # We patch docker to use all the HD available in GH action free runners
    - name: Patch Docker Daemon data-root
      run: |
        DOCKER_DATA_ROOT='/mnt/var/lib/docker'
        DOCKER_DAEMON_JSON='/etc/docker/daemon.json'
        sudo mkdir -p "${DOCKER_DATA_ROOT}"
        jq --arg dataroot "${DOCKER_DATA_ROOT}" '. + {"data-root": $dataroot}' "${DOCKER_DAEMON_JSON}" > "/tmp/docker.json.tmp"
        sudo mv "/tmp/docker.json.tmp" "${DOCKER_DAEMON_JSON}"
        sudo systemctl restart docker

    - name: Login to DockerHub Registry
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Set Push options
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: echo "BUILD_ARGS=--push --only-target-package --pull" >> $GITHUB_ENV

    - name: Install deps
      run: |
        sudo -E make deps

    - name: Validate 🌳
      run: |
        make validate

    - name: Build packages 🔧
      run: |
        sudo -E make build
        ls -liah $PWD/build

    - name: Publish to DockerHub 🚀
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        sudo -E make publish-repo
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.flavor }}
        path: build
  iso:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
       include:
         - flavor: "opensuse"
         - flavor: "fedora"
    steps:
    - uses: actions/checkout@v2
    - name: Download result for build
      uses: actions/download-artifact@v2
      with:
        name: build-${{ matrix.flavor }}
        path: build
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y xorriso squashfs-tools dosfstools
        sudo -E make deps

    - name: Build ISO from local build 🔧
      if: ${{ github.event_name != 'schedule' }}
      run: |
        sudo -E make local-iso
        COS_VERSION=$(yq r packages/cos/definition.yaml 'version')
        mv *.iso cOS-$COS_VERSION.iso
        mv *.sha256 cOS-$COS_VERSION.iso.sha256

    - name: Build ISO from remote repositories 🔧
      if: ${{ github.event_name == 'schedule' }}
      run: |
        sudo -E make iso
        COS_VERSION=$(yq r packages/cos/definition.yaml 'version')
        mv *.iso cOS-$COS_VERSION.iso
        mv *.sha256 cOS-$COS_VERSION.iso.sha256

    - uses: actions/upload-artifact@v2
      with:
        name: cOS-${{ matrix.flavor }}.iso.zip
        path: |
          *.iso
          *.sha256
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: luet-build-${{ matrix.flavor }}.log
        path: isowork/*.log

  qemu:
      runs-on: ubuntu-latest
      needs: iso

      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - uses: actions/checkout@v2
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-system qemu-kvm
          sudo -E make deps
          sudo luet install -y utils/packer

      - name: Build QEMU Image 🔧
        run: |
          PACKER_ARGS="-var='accellerator=none' -var='sleep=5m' -only qemu" make packer
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.qcow
          path: |
            packer/*.tar.gz

  qemu-vagrant:
      runs-on: ubuntu-latest
      needs: iso

      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - uses: actions/checkout@v2
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-system qemu-kvm
          sudo -E make deps
          sudo luet install -y utils/packer

      - name: Build QEMU Image 🔧
        run: |
          PACKER_ARGS="-var='accellerator=none' -var='sleep=5m' -var='vagrant=true' -only qemu" make packer
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}-QEMU.box
          path: |
            packer/*.box

  vbox:
      runs-on: macos-10.15
      needs: iso
      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - uses: actions/checkout@v2
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip

      - name: Install deps
        run: |
          brew tap hashicorp/tap
          brew install hashicorp/tap/packer
      - name: Build VBox Image 🔧
        run: |
          PACKER_ARGS="-var='sleep=5m' -only virtualbox-iso" make packer
          ls packer
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.ova
          path: |
            packer/*.tar.gz

  vbox-vagrant:
      runs-on: macos-10.15
      needs: iso
      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - uses: actions/checkout@v2
      - name: Download ISO
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip

      - name: Install deps
        run: |
          brew tap hashicorp/tap
          brew install hashicorp/tap/packer
      - name: Build VBox Image 🔧
        run: |
          PACKER_ARGS="-var='sleep=5m' -var='vagrant=true' -only virtualbox-iso" make packer
          ls packer

      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}-vbox.box
          path: |
            packer/*.box

  tests:
      runs-on: macos-10.15
      needs: vbox-vagrant
      strategy:
        matrix:
          include:
            - flavor: "opensuse"
#            - flavor: "fedora"
      steps:
      - name: Install Go
        uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: Download vagrant box
        uses: actions/download-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}-vbox.box
          path: packer

      - name: Run tests 🔧
        run: |
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          make test
