name: Build cOS
on:
  pull_request:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo df -h
      - run: sudo rm -rf /usr/local/lib/android
      - run: sudo df -h
      - run: sudo rm -rf /usr/share/dotnet
      - run: sudo df -h