name: Build cOS Examples
on: 
 pull_request:
   paths:
     - conf/**
     - packages/**
     - make/**
     - .github/**
     - Makefile
     - tests/**
     - examples/**
concurrency:
  group: ci-Examples-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  docker-build-example-cos-official:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - name: Run make deps
        run: |
          sudo -E make deps
          sudo luet install -y toolchain/yq
      - name: Build cos-official 🔧
        shell: 'script -q -e -c "bash {0}"'
        run: |
          cd examples/cos-official
          docker build . -t cos-official
  docker-build-example-scratch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - name: Run make deps
        run: |
          sudo -E make deps
          sudo luet install -y toolchain/yq
      - name: Build scratch 🔧
        shell: 'script -q -e -c "bash {0}"'
        run: |
          cd examples/scratch
          docker build . -t scratch
  docker-build-example-standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.16'
      - name: Run make deps
        run: |
          sudo -E make deps
          sudo luet install -y toolchain/yq
      - name: Build standard 🔧
        shell: 'script -q -e -c "bash {0}"'
        run: |
          cd examples/standard
          docker build . -t standard
