name: build
on:
  schedule:
    - cron:  '0 20 * * *'
  pull_request:
    paths:
      - 'conf/**'
      - 'packages/**'
      - 'make/**'
      - '.github/**'
      - 'Makefile'
      - 'tests/**'
  create:
    tags:
      - v*

concurrency: 
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - flavor: "opensuse"
    env:
      FLAVOR: ${{ matrix.flavor }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2

      - run: |
          git fetch --prune --unshallow

      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master

      - name: "Set PR options"
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "BUILD_ARGS=--no-spinner --only-target-package --live-output --pull" >> $GITHUB_ENV

      - name: "Set Branches options"
        if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master' }}
        run: echo "BUILD_ARGS=--no-spinner --only-target-package --live-output --pull" >> $GITHUB_ENV

      - name: Install deps
        run: |
          sudo -E make deps
          sudo -E luet install -y --config .github/.luet.yaml toolchain/luet-mtree

      - name: Validate 🌳
        run: |
          make validate

      - name: Build packages 🔧
        run: |
          sudo -E make build
          ls -liah $PWD/build
          sudo chmod -R 777 $PWD/build
      - name: Generate manifests
        run: |
          for f in build/*tar*; do
            sudo -E luet mtree -- generate $f -o "$f.mtree"
          done
      - name: Append manifests to metadata
        run: |
          for f in build/*mtree; do
            BASE_NAME=`basename -s .package.tar.zst.mtree $f`
            sudo -E .github/append_manifests.py build/$BASE_NAME.metadata.yaml $f mtree
          done
      - name: Create repo
        run: |
          sudo -E make create-repo
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.flavor }}
          path: build
          if-no-files-found: error
      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: iso
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}