name: docker-green-x86_64
on: 
 pull_request:
   paths:
     - conf/**
     - packages/**
     - make/**
     - .github/**
     - Makefile
     - tests/**
concurrency:
  group: ci-docker-green-x86_64-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  docker-build-green:
    runs-on: ubuntu-latest
    env:
      FLAVOR: green
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker ♻
        if: always()
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Install CI plugins
        run: |
            sudo cp -rfv .github/plugins/* /usr/bin/
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cos-builder
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true # loads it locally, so it can be used from docker client
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
      - name: Run build on docker
        run: |
          docker run \
            -e FINAL_REPO="quay.io/costoolkit/releases-green" \
            -i --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $PWD:/build/ \
            ${{ steps.meta.outputs.tags }}
