name: Cancel lingering jobs
on:
  workflow_run:
    workflows: ["Build cOS Pull requests - arm64", "Build cOS Pull requests - docker", "Build cOS Pull requests", "Build cOS Examples"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        with:
          ignore_sha: true # ignore sha becuase we want to cancel all pending jobs
          workflow_id: ${{ github.event.workflow.id }}