name: Cloud cleaner

on:
  schedule:
    - cron:  '0 */8 * * *' # every 8 hours
  workflow_dispatch:
    inputs:
      hours:
        description: "Hours to check from the current time for running instances"
        required: false
        default: "8"
jobs:
  clean:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      HOURS: ${{ github.event.inputs.hours }}
    steps:
      - name: Get instances
        run: |
          .github/cloud-cleaner.sh
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: instances.txt
          path: instances.txt
          if-no-files-found: warning
      # this is where we would put a webhook to the slack channel IF WE HAD ONE