name: Nightly image builds

on:
  schedule:
    - cron:  '0 20 * * *'
jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        git fetch --prune --unshallow

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y xorriso squashfs-tools dosfstools qemu
        sudo -E make deps
        sudo luet install -y utils/packer
    - name: Build ISO 🔧
      run: |
        sudo -E make iso
        cp -rfv *.iso cOS.iso
    - name: Build QEMU Image 🔧
      run: |
        ISO=$PWD/cOS.iso PACKER_ARGS="-var='accellerator=none' -var='sleep=5m' -only qemu" make packer
    - uses: actions/upload-artifact@v2
      with:
        name: ISO
        path: |
          *.iso
          *.sha256
    - uses: actions/upload-artifact@v2
      with:
        name: QEMU
        path: |
          packer/*-qemu.tar.gz
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: build-log
        path: isowork/*.log
