name: iso
on:
  workflow_dispatch: # for triggering it manually
  workflow_run:
    workflows: [ "build" ]
    types:
      - completed
concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  iso:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - flavor: "opensuse"
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set pending
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{ github.workflow }}
          description: 'Build the iso'
          state: 'pending'
          sha: ${{ github.event.workflow_run.head_sha }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow.id }}
          commit: ${{ github.event.workflow_run.head_sha }}
          name: build-${{ matrix.flavor }}
          path: build

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso squashfs-tools
          sudo -E make deps

      - name: Build ISO from local build 🔧
        if: github.event_name != 'schedule' && !startsWith(github.ref, 'refs/tags/')
        run: |
          sudo -E make local-iso

      - name: Build ISO from remote repositories 🔧
        if: github.event_name == 'schedule' || startsWith(github.ref, 'refs/tags/')
        run: |
          sudo -E make iso
      - uses: actions/upload-artifact@v2
        with:
          name: cOS-${{ matrix.flavor }}.iso.zip
          path: |
            *.iso
            *.sha256
          if-no-files-found: error
      - name: Set success
        if: success()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{ github.workflow }}
          description: 'Build the iso'
          state: 'success'
          sha: ${{ github.event.workflow_run.head_sha }}
      - name: Set failure
        if: failure()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{ github.workflow }}
          description: 'Build the iso'
          state: 'failure'
          sha: ${{ github.event.workflow_run.head_sha }}