name: publish
on:
  workflow_dispatch: # for triggering it manually

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/') &&  github.event.workflow_run.conclusion == 'success'
    strategy:
      matrix:
        include:
          - flavor: "opensuse"
          - flavor: "fedora"
    env:
      FLAVOR: ${{ matrix.flavor }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: packer-qemu.yaml
          commit: ${{ github.event.workflow_run.head_sha }}
          name: build-${{ matrix.flavor }}
          path: build
      - run: |
          git fetch --prune --unshallow

      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master

      # We patch docker to use all the HD available in GH action free runners
      - name: Patch Docker Daemon data-root
        run: |
          DOCKER_DATA_ROOT='/mnt/var/lib/docker'
          DOCKER_DAEMON_JSON='/etc/docker/daemon.json'
          sudo mkdir -p "${DOCKER_DATA_ROOT}"
          jq --arg dataroot "${DOCKER_DATA_ROOT}" '. + {"data-root": $dataroot}' "${DOCKER_DAEMON_JSON}" > "/tmp/docker.json.tmp"
          sudo mv "/tmp/docker.json.tmp" "${DOCKER_DAEMON_JSON}"
          sudo systemctl restart docker

      - name: Login to Quay Registry
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
      - name: Set Push options
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: echo "BUILD_ARGS=--push --only-target-package --pull" >> $GITHUB_ENV

      - name: Install deps
        run: |
          sudo -E make deps

      - name: Publish to DockerHub 🚀
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          sudo -E make publish-repo

  github-release:
    if: startsWith(github.ref, 'refs/tags/') && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - flavor: "opensuse"
          - flavor: "fedora"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Download Iso
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: iso.yml
          commit: ${{ github.event.workflow_run.head_sha }}
          name: cOS-${{ matrix.flavor }}.iso.zip
          path: release
      - name: Download vbox image
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: packer-vbox.yml
          commit: ${{ github.event.workflow_run.head_sha }}
          name: cOS-${{ matrix.flavor }}-vbox.box
          path: release
      - name: Download OVA image
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: packer-qemu.yml
          commit: ${{ github.event.workflow_run.head_sha }}
          name: cOS-${{ matrix.flavor }}.ova
          path: release
      - name: Download QCOW image
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: packer-qemu.yml
          commit: ${{ github.event.workflow_run.head_sha }}
          name: cOS-${{ matrix.flavor }}.qcow
          path: release
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}