name: test
on:
  workflow_dispatch: # for triggering it manually

concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      VAGRANT_CPU: 3
      VAGRANT_MEMORY: 10240
    runs-on: macos-10.15
    strategy:
      matrix:
        flavor: ["opensuse"]
        test: ["test-features", "test-smoke", "test-fallback", "test-recovery", "test-upgrades-images-signed", "test-upgrades-images-unsigned"]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Install Go
        uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: Download vagrant box
        uses: actions/download-artifact@v2
        with:
          workflow: packer-vbox
          commit: ${{ github.event.pull_request.head.ref || github.ref }}
          name: cOS-${{ matrix.flavor }}-vbox.box
          path: packer

      - name: Run tests 🔧
        run: |
          export GOPATH="/Users/runner/go"
          go get -u github.com/onsi/ginkgo/ginkgo
          go get -u github.com/onsi/gomega/...
          PATH=$PATH:$GOPATH/bin
          make test-clean
          make vagrantfile
          make prepare-test
          make ${{ matrix.test }}
      - uses: actions/upload-artifact@v2
        if: failure() && contains(matrix.test, 'upgrade')
        with:
          name: cOS-${{ matrix.test }}.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn
      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}