requires:
- name: "base"
  category: "distro"
  version: ">=0"

prelude:
{{ if .Values.distribution }}
{{if eq .Values.distribution "opensuse" }}
- zypper in -y wget && zypper install -y -t pattern devel_basis
{{else if eq .Values.distribution "fedora" }}
- dnf install -y wget "@Development Tools"
{{else if eq .Values.distribution "ubuntu" }}
# We have to add || true as system post-install of grub is broken due to efi and pc being installed together
- apt-get install -y build-essential wget || true
{{end}}
{{end}}
- wget https://golang.org/dl/go{{.Values.version}}.linux-{{.Values.arch}}.tar.gz -O golang.tar.gz

steps:
- tar -C /usr/local -xzf golang.tar.gz
